baseURL = "https://stacks101.com"
languageCode = "en-us"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = false

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  blog = "/:year/:month/:slug/"
  page = "/:slug/"

[params]
  company = "Stacks 101"
  title = "Stacks 101"
  tagline = "Tutorials, lessons, and info about Stacks (STX)"
  description = "Community curated Stacks (STX) knowledge, resources, and educational content."
  copyright = "© 2020 Absorbing Chaos"

[params.author]
  name = "Jason Schrader"
  github = "https://github.com/whoabuddy"
  sitename = "Stacks101"
  twitter = "@absorbingchaos"

# used for SEO image tags in head
[params.logo]
  img = "img/stacks-nexus-800x400.png"
  type = "image/png"
  width = "800"
  height = "400"
  alt = "The stacks nexus symbol with the metaverse gradient behind it."

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Community"
    identifier = "stx-community"
    url = "/stx-community/"
    weight = 20
  [[menu.main]]
    name = "Governance"
    identifier = "stx-governance"
    url = "/stx-governance/"
    weight = 30
  [[menu.main]]
    name = "Mining"
    identifier = "stx-mining"
    url = "/stx-mining/"
    weight = 40
    [[menu.main]]
      parent = "stx-mining"
      name = "FAQ"
      identifier = "stx-mining-faq"
      url = "/stx-mining/faq"
      weight = 10
    [[menu.main]]
      parent = "stx-mining"
      name = "Resources"
      identifier = "stx-mining-resources"
      url = "/stx-mining/resources"
      weight = 20
    [[menu.main]]
      parent = "stx-mining"
      name = "Setup"
      identifier = "stx-mining-setup"
      url = "/stx-mining/setup"
      weight = 30
    [[menu.main]]
      parent = "stx-mining"
      name = "Stacks-Dump"
      identifier = "stx-mining-stacks-dump"
      url = "/stx-mining/stacks-dump"
      weight = 40
  [[menu.main]]
    name = "Stacking"
    identifier = "stx-stacking"
    url = "/stx-stacking/"
    weight = 50
    [[menu.main]]
      parent = "stx-stacking"
      name = "FAQ"
      identifier = "stx-stacking-faq"
      url = "/stx-stacking/faq"
      weight = 10
    [[menu.main]]
      parent = "stx-stacking"
      name = "Resources"
      identifier = "stx-stacking-resources"
      url = "/stx-stacking/resources"
      weight = 20
  [[menu.main]]
    name = "Videos"
    identifier = "stx-videos"
    url = "/stx-videos/"
    weight = 60
